# Use `brew bundle` to install the packages listed below

cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'ack'
brew 'archey'
brew 'coreutils'
brew 'git'
brew 'grc'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'openssl'
brew 'node'
brew 'readline'
brew 'spaceman-diff'
brew 'spark'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'z'
brew 'zsh'

cask 'alfred'
cask 'caffeine'
cask 'cd-to'
cask 'firefox'
cask 'iterm2'
cask 'rectangle'
cask 'google-chrome'
cask 'opera'
cask 'nvalt'
cask 'sequel-pro'
cask 'transmit'
cask 'spotify'
cask 'imagealpha'
cask 'imageoptim'
cask 'dash'
cask 'insomnia'

# Quick Look plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'qlprettypatch'

# Nerd Fonts required for powerlevel9k theme
cask 'font-hack-nerd-font'
