-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL U2713HM 7JNY539BA0RL",
  mode = "2560x1440@59.95",
  position = "2560x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Thermotrex Corporation TL140BDXP01-0",
  mode = "2560x1440@120.00",
  position = "512x0",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Dell Inc. DELL U2713HM 7JNY539BA0RL", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Dell Inc. DELL U2713HM 7JNY539BA0RL" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Dell Inc. DELL U2713HM 7JNY539BA0RL" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Thermotrex Corporation TL140BDXP01-0", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Thermotrex Corporation TL140BDXP01-0" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Thermotrex Corporation TL140BDXP01-0" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Dell Inc. DELL U2713HM 7JNY539BA0RL" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Dell Inc. DELL U2713HM 7JNY539BA0RL" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Dell Inc. DELL U2713HM 7JNY539BA0RL" })
